### ISSUE TITLE
코드 스타일 정리

### ISSUE THREAD

**Issue by turastory** [desingdeveloperdayday/lovelessgeek_housemanager_api#6]
서로 간의 코드 스타일을 같은걸로 유지하면 커밋을 할 때 코드를 깔끔하게 유지할 수 있습니다!

안드로이드 스튜디오를 사용하고 있으니 Code Style을 따로 맞출 필요는 없을 것 같습니다.

- [Reformat Code] 기능을 사용하면 코드를 정리할 수 있는데 단축키는 다음과 같습니다..
  
  Windows: [Ctrl]-[Alt]-[L]
  Mac: [Cmd]-[Option]-[L]

- 커밋을 하기 전에 [Reformat Code]를 체크하면 변경된 파일을 대상으로 Reformat을 실행한 후 Commit 됩니다.

확인하시고 이 이슈는 닫아주세요!

**Comment by turastory** [comment]
정리가 되면 Wiki나 README에 추가하려고 합니다

**Comment by rapsealk** [comment]
확인했습니다. 감사합니다 👍
